### ISSUE TITLE
Unable to update directly through the app while not runing as root user

### ISSUE THREAD

**Issue by n5q** [AndroidAppz/LuckyPatcher#6]
As the title suggests, it is currently impossible to update the app directly without having to download the latest APK from the website. The update prompt functions as normal however after asking to install the new update Lucky Patcher starts the Package Installer activity withn the app itself rather than making a new task for it so when Package Installer restarts the app in order to update it the Package Installer closes itself in the process as it is part of the same activity.

I am aware that it is possible to navigate to Lucky Patcher's downloads folder and install the APK as you normally would but it is still an inconvenience to do

**Comment by Bluscream** [comment]
This is no offiicial LP support repo. You should use the contact details from within the app.
